### ISSUE TITLE
Redirect after login does not work

### ISSUE THREAD

**Issue by HofmT** [matt-ankerson/vue-adal#2]
Hi Matt,

Thank you for sharing your library. It helped me very much. However I still have the following issue:

I modified your example to redirect any user not logged in to a seperate loginpage. Clicking on the login button will trigger the Azure AD authentication process. After a successful login I want the user to be redirected to the root index ('/').
In order to achieve that I set my redirectUri to http://127.0.0.1:8081/ and also set the config variable navigateToLoginRequestUrl to false.

Now what happens after a login is that I do get redirected to the root index however the page ist completely blank. There is no error but the content of the site is simply not loaded. Hitting a refresh button afterwards will load the UI into the browser.

Do you have any idea what the reason could be? Right now , I assume that it could have something to do with the way your initialize method for ADAL works but I'm not sure.

I appreciate any help. Thank you!

Kind regards
Tobias

**Comment by adnanchang** [comment]
Hi!

I am not sure if you've already solved this but try this:

Inside your router config:

```
const router = new Router({
  mode: 'history',
```

**Comment by danielelkington** [comment]
I also had this problem, and didn't want to switch to 'history' mode. Instead the issue was fixed by adding a `resolve()` call to the authentication initialize() function under `this.authenticationContext.handleWindowCallback()`.

```initialize() {
  this.authenticationContext = new AuthenticationContext(config);

  return new Promise((resolve, reject) => {
    if (this.authenticationContext.isCallback(window.location.hash) || window.self !== window.top) {
      // redirect to the location specified in the url params.
      this.authenticationContext.handleWindowCallback();
      resolve(); // <------------------- Added this line here
    }
    else {...
```

**Comment by andreav** [comment]
Thank you @danielelkington ! Your fix solved the issue!
